# required
name: RainWorld
version: 0.3
main: org.rainworld.RainWorld
# optional
description: Clouds atop mountains, captured in air. Terraform rain flows, better beware.
api-version: 1.19
author: leonk.dev 
website: info.dankpiss.art
commands:
  rain: 
    description: "Let it rain!"
    usage: /<command> [start|stop|cloud|watch|ignore|config]