# required
name: RainCraft
version: 0.3
main: org.rainworld.RainBlock
# optional
description: Mountains form clouds which rain moving sediment to form rivers, lakes and more mountains.
api-version: 1.19
author: leonk.dev 
website: info.dankpiss.art
commands:
  clouds: 
    description: "Enables cloud spawning."
